name: dune_ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: 4.12
        opam-repository: default
        allow-prelease-opam: false
        opam-pin: true
        opam-depext: true
        opam-local-packages: "*.opam"
        opam-disable-sandboxing: false
        dune-cache: false
        cache-prefix: v1
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies
      run: opam install --deps-only .

    - name: Build
      run: dune build

    - name: Test
      run: dune runtest
