name: dune_ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: 5.1
        opam-repository: default

    - name: Install Dependencies
      run: opam install --deps-only .

    - name: Build
      run: dune build

    - name: Test
      run: dune runtest
