name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: 4.12

      - name: Install dependencies
        run: opam install --deps-only --locked .

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest
