name: dune_ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions: read-all

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up OCaml
          uses: ocaml/setup-ocaml@v2
          with:
            opam-repository: official
        - name: Build and Test with Dune
          run: |
            opam install . --deps-only --with-test
            opam exec -- dune build
            opam exec -- dune runtest